# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [10]:
# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

array = np.random.randint(1,21,size = (5,5))

print("Original Array")

print(array)

print("Modified Array")

array[:,2] = 1

print(array)

Original Array
[[ 4  6  3  9  3]
 [20  1  2 20 12]
 [18 17 13 17  8]
 [ 9 20 10 13  1]
 [16 20 18  9  5]]
Modified Array
[[ 4  6  1  9  3]
 [20  1  1 20 12]
 [18 17  1 17  8]
 [ 9 20  1 13  1]
 [16 20  1  9  5]]


In [16]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr = np.arange(1,17).reshape(4,4)

print("Original Array")

print(arr)

print("Modified Array")

np.fill_diagonal(arr,0)

print(arr)

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [27]:
## Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr = np.arange(1,37).reshape(6,6)

print("Original Array")

print(arr)

print("Extracted Rows and Columns")

print(arr[2:5,1:4])

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Extracted Rows and Columns
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [33]:
## Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr = np.arange(1,26).reshape(5,5)

print("Original Array")

print(arr)

print("Extracted Border elements")

border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print("Border elements:")
print(border_elements)



Original Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Extracted Border elements
Border elements:
[ 1  2  3  4  5 21 22 23 24 25  6 11 16 10 15 20]


In [35]:
## Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

array_1 = np.random.randint(1,11,size=(3,4))
array_2 = np.random.randint(1,11,size=(3,4))
print("Array1")
print(array_1)
print("Array2")
print(array_2)

addition = array_1+array_2

substraction = array_1-array_2

Multiplication = array_1*array_2

division = array_1/array_2

print("elements wise addition")
print(addition)
print("elements wise substraction")
print(substraction)
print("elements wise multiplication")
print(Multiplication)
print("elements wise division")
print(division)

Array1
[[ 1  8  9  7]
 [10  6  2  7]
 [ 5  7  5  6]]
Array2
[[10  3  3 10]
 [ 4  1  9  2]
 [ 4  4  6  4]]
elements wise addition
[[11 11 12 17]
 [14  7 11  9]
 [ 9 11 11 10]]
elements wise substraction
[[-9  5  6 -3]
 [ 6  5 -7  5]
 [ 1  3 -1  2]]
elements wise multiplication
[[10 24 27 70]
 [40  6 18 14]
 [20 28 30 24]]
elements wise division
[[0.1        2.66666667 3.         0.7       ]
 [2.5        6.         0.22222222 3.5       ]
 [1.25       1.75       0.83333333 1.5       ]]


In [46]:
## Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr = np.arange(1,17).reshape(4,4)

print("Array")

print(arr)

print("Compute - row - wise")

row_sum = np.sum(arr,axis=1)

print(row_sum)

print("Compute - column - wise")

column_sum = np.sum(arr,axis=0)

print(column_sum)





Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Compute - row - wise
[10 26 42 58]
Compute - column - wise
[28 32 36 40]


In [49]:
## Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr = np.random.randint(1,21,size=(5,5))

print(arr)

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np.var(arr)

print("Mean:",mean)
print("Median:",median)
print("Standard deviation:",std_dev)
print("Variance:",var)

[[11 20 20  3 10]
 [ 3 11  8 20 10]
 [16  7 11  1 10]
 [ 5 11  9 11 13]
 [14  1 18  4 19]]
Mean: 10.64
Median: 11.0
Standard deviation: 5.7819028009816975
Variance: 33.4304


In [50]:
## Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr = np.arange(1,10).reshape(3,3)

print(arr)

# Normalization

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
normalization = (arr-mean)/std_dev

print("Normalized Array:")
print(normalization)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
