### Numpy

In [2]:
## Numpy is a fundamental library for scientific computing in python.
## It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. 

In [3]:
import numpy as np

In [15]:
## 1-D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4,5])

print(arr2)
print(arr2.shape)
arr2.reshape(1,5)

[1 2 3 4 5]
(5,)


array([[1, 2, 3, 4, 5]])

In [14]:
# 2-D array

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr2)

print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [16]:
## Inbuilt - functions

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
## Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
## Attributes of Numpy Array

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Array:\n", arr)

print("Shape:", arr.shape)

print("Data type:", arr.dtype)

print("Dimension:", arr.ndim)

print("Size (No. of Elements):", arr.size)

print("Item size (in bytes):", arr.itemsize)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Data type: int64
Dimension: 2
Size (No. of Elements): 10
Item size (in bytes): 8


In [28]:
## Numpy Vectorized Operation

In [31]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

## Element wise addition

print("Addition:", arr1 + arr2)

## Element wise Substraction

print("Substraction:",  arr1 - arr2)

## Element wise multiplication

print("Multiplication:", arr1 * arr2)

## Element wise Division

print("Division:", arr1 / arr2)

Addition: [ 7  9 11 13 15]
Substraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [32]:
## Universal function

arr = np.array([2,3,4,5,6])

## sqrt

print(np.sqrt(arr))

## Exponential

print(np.exp(arr))

## Sine

print(np.sin(arr))

### Natural log

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [33]:
## Array - slicing and indexing

In [34]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
 arr[0][0]

np.int64(1)

In [42]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [48]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
arr[1:,1:-1]

array([[ 6,  7],
       [10, 11]])

In [53]:
### Modify array elements

In [54]:
arr[0,0] = 85

print(arr)

[[85  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
print(arr[2,3])

12


In [65]:
## Statstical Concepts - Normalization

## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation

mean = np.mean(data)

std_dev = np.std(data)

## Normalize the data

Normalized_data = (data - mean) / std_dev

print("Normalized data:",Normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [67]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean

mean = np.mean(data)
print("Mean:",mean)

## Median

median = np.median(data)
print("Median:",median)

# Standard Deviation

std_dev = np.std(data)
print("Standard Deviation:",std_dev)

# Variance

var = np.var(data)
print("Variance:",var)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [68]:
## Logical Operations

In [71]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data > 5]

data[data < 5]

array([1, 2, 3, 4])

In [72]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [73]:
data[(data>=5) and (data<=8)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### THE END