In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
print(arr1)

[1 2 3 4 5]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
print(arr1.shape)

(5,)


In [6]:
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
arr1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])